name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,observe,ui]
      - name: Lint
        run: |
          ruff check .
          ruff format --check .
      - name: Type check
        run: mypy
      - name: Tests
        run: pytest -q
      - name: Build docs
        run: mkdocs build
      - name: Sample report
        run: noema run --task interruption_count --model dummy --ticks 10 --report report.html
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.html
